name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
         update-conda: true
         python-version: ${{ matrix.python-version }}
         conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: python --version
      - run: conda install flake8-docstrings pyaml pytest python=${{ matrix.python-version }}
      - name: Build
        shell: bash -l {0}
        run: |
          pip install -e .[test] 
      - name: Test
        shell: bash -l {0}
        run: |
          pytest tests 
