name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
         update-conda: true
         python-version: ${{ matrix.python-version }}
         conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: python --version
      - run: conda install python=${{ matrix.python-version }}
      - name: Build
        run: |
          pip3 install -e .[test,doc] 
          python setup.py install
      - name: Test
        run: |
          pytest --cache-clear --cov=. tests/ | tee pytest-coverage.txt
      - name: pytest-coverage-commentator
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
          

